### ISSUE TITLE
[STYLE] 방문의사 페이지 퍼블리싱

### ISSUE THREAD

**Issue by wldusdn** [Ureka-project/WHERE_ARE_YOU_GOING_DAENG_DAENG_FE#33]
# 🌈 디자인 스타일 가이드

## ✅ 구현할 화면이나 컴포넌트를 작성해주세요

- [x] 방문의사목록
- [x] 방문의사등록
- [x] 내방문예정리스트

## 📸 구현한 화면을 첨부해주세요

![image](https://github.com/user-attachments/assets/c5909504-2ee1-4778-b623-b19c553ea63a)
![image](https://github.com/user-attachments/assets/4f237dd9-50b7-481b-8167-9a6dc252617c)

## ✨ 구현 화면
- 원래 mui 달력과 테이블을 쓰려고 했는데 디자인 변경이 잘 안돼서 그냥 만들었습니다..
- 방문일정은 당일부터 일주일간 일정을 보여주고 이전 일정을 보고 싶으면 지난 일자 아무거나 클릭시 이전일정을 전부 보여주는 걸로 일단 만들었습니다
- 일정이 있는 날들은 달력에 점 표시를 추가했습니다.
- 이전 일정들은 테이블에 취소선을 넣어 이전 일정이라는 느낌을 더 넣어봤습니다.ㅎㅎ
- 장소에 숫자는 api명세서에서 placeId를 넘겨줘서 일단은 그 값을 넣어놓은거고 api연동할 때 장소명 들어가게 바꿀게요!

## 💡 추가 설명
[기타 리뷰어가 참고해야 할 사항이나 추가적인 설명이 있다면 적어주세요.]
- 디자인은 제 임의로 한거라서 피드백 환영합니다 👏
- 지도때문에 여러번 리셋하느라 작업속도가 느리네요.. 밤샜는데도 아직 두페이지나 더 남았..ㅇ

**Comment by subinsong01** [comment]
디자인 너무 마음에 들어요,, 🥳 최구
