### ISSUE TITLE
[STYLE] 검색페이지 퍼블리싱

### ISSUE THREAD

**Issue by wldusdn** [Ureka-project/WHERE_ARE_YOU_GOING_DAENG_DAENG_FE#9]
# 🌈 디자인 스타일 가이드

## ✅ 구현할 화면이나 컴포넌트를 작성해주세요

- [x] 검색바
- [x] 맵
- [x] 검색목록
- [x] 필터버튼
- [x] 추천리스트 or 검색리스트

## 📸 구현한 화면을 첨부해주세요

[구현한 화면을 아래에 첨부해주세요.]

## ✨ 구현 화면
![image](https://github.com/user-attachments/assets/d5aa9ce0-3bbc-4cc1-97eb-e4d81c131f92)
## 💡 추가 설명
일단 틀만 구성.. 아직 안 끝나따..

**Comment by subinsong01** [comment]
완벽...
